### ISSUE TITLE
supported version of psql

### ISSUE THREAD

**Issue by highlowhighlow** [sqitchers/sqitch#384] opened 2018-05-23 20:08 UTC
I was trying to deploy to an RDS postgresql database from my local windows. local psql is 9.6.3, kept getting this error. Afterwards the registry schema was not created. The password is correct. I tried another installation on a linux box with psql client version of 8.4.20, same connection string, and was able to connect and create the registry schema(but got another weird error). Can you confirm if this version of sqitch is tested with psql client version of 9.6.*? Thanks

c:\bitbucket_sqitch>sqitch --version
sqitch (App::Sqitch) 0.9997

c:\bitbucket_sqitch>sqitch deploy db:pg://myuser:myuserpassword@hostname:port/dbname
Adding registry tables to db:pg://myuser:@hostname:port/dbname
psql: warning: extra command-line argument "host=hostname" ignored
psql: warning: extra command-line argument "--quiet" ignored
psql: warning: extra command-line argument "--no-psqlrc" ignored
psql: warning: extra command-line argument "--no-align" ignored
psql: warning: extra command-line argument "--tuples-only" ignored
psql: warning: extra command-line argument "--set" ignored
psql: warning: extra command-line argument "ON_ERROR_STOP=1" ignored
psql: warning: extra command-line argument "--set" ignored
psql: warning: extra command-line argument "registry=sqitch" ignored
psql: warning: extra command-line argument "-c" ignored
psql: warning: extra command-line argument "SHOW" ignored
psql: warning: extra command-line argument "server_version_num" ignored
psql: FATAL:  password authentication failed for user "myuser"
"psql.exe" unexpectedly returned exit value 2

**Comment by patricia-finra** [comment] 2018-05-23 20:36
I guess I found the answer myself:

App/Sqitch version 0.9998

Sqitch is a database change management application. It currently supports PostgreSQL 8.4+...

**Comment by theory** [comment] 2018-05-23 20:46
So, is your problem fixed, @patricia-finra?

**Comment by patricia-finra** [comment] 2018-05-23 21:01
Not really. I have concerns that the psql client version is so behind. If we decide to use sqitch for our project, it means we have to maintain a separate, quite dated psql client executable. Is there any reason this can not be updated more often?

**Comment by patricia-finra** [comment] 2018-05-23 21:41
Yes it is in the path and:
c:\bitbucket_sqitch>where psql
c:\Program Files\PostgreSQL\9.6\bin\psql.exe
c:\bitbucket_sqitch>psql --version
psql (PostgreSQL) 9.6.3

Have you tested it against 9.6.* psql client? I remember there was some additional options with the later psql client versions.

**Comment by theory** [comment] 2018-05-23 21:44
Yes, it's used regularly with Postgres 10 and Postgres 9.6. I suspect the problem is that the new connection code added in #375 wasn't properly tested on Windows. Would you try running it with the patch I pasted above?

**Comment by patricia-finra** [comment] 2018-05-23 21:50
I'll have to request admin rights for that. Will try tomorrow and update. Thanks for the prompt replies.

**Comment by patricia-finra** [comment] 2018-05-25 20:13
finally got local admin and applied the patch above. Still same thing

**Comment by fleetside72** [comment] 2018-05-30 19:50
@patricia-finra I don't know if you are aware, but WSL (Windows Subsystem for Linux) works really well for utilizing sqitch on Windows. Enable it in the Windows features, then go to the windows store and download one of the Debian based Linux distros and then you can just `apt-get install`. you can also use  pspg pager as well with psql.

**Comment by theory** [comment] 2018-05-30 19:55
What version of `psql.exe` are you running, and what version of the server?

**Comment by patricia-finra** [comment] 2018-05-30 20:26
client 9.6.3, server is 9.6.6

**Comment by theory** [comment] 2018-05-30 20:49
Looks like you need to set a password. See [sqitch-passwords](/sqitchers/sqitch/blob/master/lib/sqitch-passwords.pod) for details.

**Comment by patricia-finra** [comment] 2018-05-30 21:20
I did not include the cmd since I needed to mask sensitive information, but the password was provided. It is basically the same cmd with the one I used on my linux installation(#314), it worked there but not on the windows installation.

**Comment by theory** [comment] 2018-05-30 21:44
Please paste exactly what you put on the command line, with the password obfuscated.  If the password has a space in it, though, please include a space in your obfuscated version.

**Comment by patricia-finra** [comment] 2018-05-30 21:54
$ sqitch deploy db:pg://myuser:mypswd@myhost:5432/mydb

no space or other special character in password other than a-z, A-Z, 0-9

**Comment by theory** [comment] 2018-05-30 22:04
Okay, it's gotta be that the switch to a conninfo string in d173477 borked Windows, and something somewhere needs quoting. Would you try one more change for me?

``` diff
--- a/lib/App/Sqitch.pm
+++ b/lib/App/Sqitch.pm
@@ -350,6 +350,7 @@ sub run {
         ( my $msg = shift ) =~ s/\s+at\s+.+/\n/ms;
         die $msg;
     };
+    say map { "'$_'" } @_;
     runx @_;
     return $self;
 }

**Comment by patricia-finra** [comment] 2018-05-31 15:18
Output after applying the patch(all else the same as above): looks like it took the username as dbname?

psql: FATAL:  database "myuser" does not exist
'psql.exe''user=myuser dbname=mydb host=myhost port=5432''--quiet''--no-psqlrc''--no-align''--tuples-only''--set''ON_ERROR_STOP=1''--set''registry=sqitch''--file''deploy\appschema.sql'
not ok
"psql.exe" unexpectedly returned exit value 2

Deploy failed

**Comment by theory** [comment] 2018-05-31 15:40
Er, that doesn't look right. Did you make the line exactly what I have above? It looks like you instead pasted

    say map { "$_''" } @_;

**Comment by patricia-finra** [comment] 2018-05-31 15:51
hm.. I did a cut and paste, not trusting myself knowing I don't know enough about perl.

**Comment by theory** [comment] 2018-05-31 16:04
Bah, no, you pasted it right, I'm just reading it wrong. Anyway, it's passing `user=myuser dbname=mydb host=myhost port=5432` as a single argument, which is correct, and should *just work.* That's because IPC::System::Simple's `runx` function should not shell out; there are no special notes about quoting values in [the docs](https://metacpan.org/pod/IPC::System::Simple#WINDOWS-SPECIFIC-NOTES). But let's test it to make sure. Remove that `say` line and make this change:

``` patch
--- a/lib/App/Sqitch.pm
+++ b/lib/App/Sqitch.pm
@@ -350,7 +350,7 @@ sub run {
         ( my $msg = shift ) =~ s/\s+at\s+.+/\n/ms;
         die $msg;
     };
-    runx @_;
+    runx $self->quote_shell( @_ );
     return $self;
 }
 ```

**Comment by patricia-finra** [comment] 2018-05-31 16:53
phew.. passed this. now getting this:

  + appschema .. not ok
""psql.exe" "user=myuser dbname=mydb host=myhost port=5432" "--quiet" "--no-psqlrc" "--no-align" "--tuples-only" "--set" "ON_ERROR_STOP=1" "--set" "registry=sqitch" "--file" "deploy\appschema.sql"" failed to start: "The system cannot find the path specified"

Deploy failed

Is this referring to the deploy script? it is where it is supposed to be relative to current directory: psql is in the path too. 
c:\bitbucket_sqitch>dir deploy
 
 Directory of c:\bitbucket_sqitch\deploy

05/23/2018  11:44 AM    <DIR>          .
05/23/2018  11:44 AM    <DIR>          ..
05/23/2018  11:44 AM                82 appschema.sql
               1 File(s)             82 bytes
               2 Dir(s)  87,368,708,096 bytes free

**Comment by theory** [comment] 2018-05-31 16:56
Hrm. What version of IPC::System::Simple do you have?

    perl -MIPC::System::Simple -e "print IPC::System::Simple->VERSION, qq{\n}"

Yes, that's the file, but there might be some other jiggery-pokery going on with the quoting that's mucking things up.

**Comment by patricia-finra** [comment] 2018-05-31 18:02
1.25

**Comment by theory** [comment] 2018-05-31 18:04
Well crap. @pjf: Do you have any idea what might be going on with args to `runx` on Windows?

**Comment by stefansbv** [comment] 2018-06-06 17:17
The problem is that `psql.exe` on Windows really ignores every option after the `conninfo` string and enters in interactive mode:
```
PS ...\sqitch> psql "user=postgres dbname=postgres" --quiet --command "select version()" --no-align
psql: warning: extra command-line argument "--command" ignored
psql: warning: extra command-line argument "select version()" ignored
psql: warning: extra command-line argument "--no-align" ignored
psql (9.6.2)
WARNING: Console code page (65001) differs from Windows code page (1250)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

postgres=#
```
It works if the `conninfo` string is the last parameter:
```
PS ...\sqitch> psql --quiet --command "select version()" --no-align "user=postg
res dbname=postgres"
version
PostgreSQL 9.6.2, compiled by Visual C++ build 1800, 32-bit
(1 row)
```
My first try was to move the `conninfo` statement to the end:
```
diff --git a/lib/App/Sqitch/Engine/pg.pm b/lib/App/Sqitch/Engine/pg.pm
index c6516058..f43e3871 100644
--- a/lib/App/Sqitch/Engine/pg.pm
+++ b/lib/App/Sqitch/Engine/pg.pm
@@ -64,13 +64,13 @@ has _psql => (
             push @conninfo, "$spec->[0]=$spec->[1]";
         }
 
-        push @ret => join ' ', @conninfo if @conninfo;
 
         if (my %vars = $self->variables) {
             push @ret => map {; '--set', "$_=$vars{$_}" } sort keys %vars;
         }
 
         push @ret => $self->_client_opts;
+        push @ret => join ' ', @conninfo if @conninfo;
         return \@ret;
     },
 );
```
but it is not enough, there are many places where the command option is at the end, for example:
```
psql.exe --quiet --no-psqlrc --no-align --tuples-only --set ON_ERROR_STOP=1 --set registry=sqitch "user=postgres dbname=__sqitchtest__6560" --command 'SELECT version()'
```
The test hangs, probably becouse `psql` enters in interactive mode. This works:
```
psql.exe --quiet --no-psqlrc --no-align --tuples-only --set ON_ERROR_STOP=1 --set registry=sqitch  --command 'SELECT version()' "user=postgres dbname=__sqitchtest__6560"
PostgreSQL 9.6.2, compiled by Visual C++ build 1800, 32-bit
```
The quoting is another problem, the command generated by the tests does not have quotes around the command option: `--command SELECT version()` and `conninfo`: `user=postgres dbname=__sqitchtest__6550`. 

For the test above I added and extra pair of quotes:
```
$self->_capture('--command' => "'SELECT version()'");
```
But the `conninfo` needs more work.

**Comment by theory** [comment] 2018-06-06 17:30
It should not need quoting; IPC::System::Simple will either handle the quoting or not use a shell, so not require quoting.

This feature of `psql.exe` where it ignores params after the conninfo string seems…weird.

**Comment by patricia-finra** [comment] 2018-06-07 14:56
On my windows installation having the conn info quoted results in error, whether it is at the very end or not. It executes ok without the quotes.

**Comment by theory** [comment] 2018-06-07 14:59
Yeah, it really shouldn't require quoting.

**Comment by theory** [comment] 2018-09-25 17:55
Looks like we can use the `--dbname` option for the conninfo string, according to [the docs](https://www.postgresql.org/docs/8.4/static/app-psql.html). @stefansbv, can you confirm that `-d` lets use use the conninfo string without ignoring subsequent options?

**Comment by theory** [comment] 2018-09-25 17:57
Looks like IPC::System::Simple  does not properly quote arguments on Windows, much to my surprise. I've submitted pjf/ipc-system-simple#29 to try to fix it.

**Comment by theory** [comment] 2018-09-25 17:58
BTW, the issue with args with spaces in it is a dupe of #331, though I think the switch to conninfo strings has made it worse. :-(

**Comment by theory** [comment] 2018-09-25 18:08
Let's see if 3e8975f fixes the ordering issue, at least.

**Comment by theory** [comment] 2018-09-26 13:59
Asked on #posrtgresql on Freenode, where user `cartan` tested it for me on the command-line, finding that using `--dbname` does in fact appear to address the problem:

    psql --dbname "user=postgres dbname=postgres" --quiet --command "select version()" --no-align

**Closed by theory** 2018-09-26 13:59 UTC
Labels: bug, engine

**Comment by namdevrathod** [comment] 2019-05-21 10:19
Worked for me
psql  -c "CREATE DATABASE exampledb" postgres://dbuser:password@localhost:5432/postgres

**Comment by TechnicallyMay** [comment] 2020-04-29 18:32
I'm using postgres 12, and having this issue. I see the resolution here, but I'm not sure how to apply this to the sqitch deploy. No matter how I seem to try it, I'm still seeing the `Extra command line arguments ignored` issue.

**Comment by theory** [comment] 2020-04-30 13:41
What version are you using, @TechnicallyMay? This issue was fixed in v0.9998.

**Comment by TechnicallyMay** [comment] 2020-04-30 16:38
I'm running v1.0. I was finally able to resolve by deleting the file C:/Windows/System32/sqitch. I may have done something wrong during installation.

**Comment by saosebastiao** [comment] 2020-06-23 17:39
Running 1.1.0, running into the same issue

**Comment by theory** [comment] 2020-06-26 18:17
Make sure you have the latest version of IPC::System::Simple installed, @saosebastiao. I mean, it shouldn't matter with Sqitch v1.1.0, but maybe?

**Comment by saosebastiao** [comment] 2020-06-26 22:30
Manually upgrading IPC::System::Simple did solve that problem for me, thank you.
