### ISSUE TITLE
Missing URL for install

### ISSUE THREAD

**Issue by lukepatrick** [sqitchers/sqitch#537] opened 2020-08-04 17:00 UTC
in the documents for Docker:
https://sqitch.org/download/docker/
`curl -L https://git.io/fAX6Z` produces "No url found for fAX6Z"

**Comment by theory** [comment] 2020-08-04 17:57
New URL is https://git.io/JJKCn. Closing as a dupe of sqitchers/docker-sqitch#28

**Closed by theory** 2020-08-04 17:57 UTC
